default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  primary:
    <<: *default
    database: money_track_development

test:
  primary:
    <<: *default
    database: money_track_test

production:
  primary:
    <<: *default
    database: moneytrack_9upt
